enable: true
organizationalUnits:
  - name: Security
  - name: Infrastructure
  - name: Workloads
  - name: Workloads/Sandbox
  - name: Workloads/Stage
serviceControlPolicies: []
taggingPolicies: []
chatbotPolicies: []
backupPolicies: []
